// Cart module: localStorage-backed cart with UI for Cart and Checkout pages
// Author: Generated by Copilot

(function () {
  const CART_KEY = "app.cart.v1";
  const CART_VERSION_KEY = "app.cart.version";
  const CURRENT_VERSION = "2"; // Version 2: USD prices

  // Format currency as USD
  const fmtCurrency = (n) => {
    if (typeof n !== 'number' || isNaN(n)) return '$0.00';
    return '$' + n.toFixed(2);
  };

  // Check and migrate cart if needed
  const checkCartVersion = () => {
    const version = localStorage.getItem(CART_VERSION_KEY);
    if (version !== CURRENT_VERSION) {
      // Clear old cart data
      localStorage.removeItem(CART_KEY);
      localStorage.setItem(CART_VERSION_KEY, CURRENT_VERSION);
      console.log('[Cart] Migrated to version', CURRENT_VERSION);
    }
  };

  checkCartVersion();

  const read = () => {
    try {
      const raw = localStorage.getItem(CART_KEY);
      const arr = raw ? JSON.parse(raw) : [];
      if (!Array.isArray(arr)) return [];
      return arr.map((x) => ({
        id: String(x.id),
        name: String(x.name || "Sản phẩm"),
        price: Number(x.price || 0),
        image: x.image || "",
        qty: Math.max(1, parseInt(x.qty || 1, 10)),
      }));
    } catch {
      return [];
    }
  };

  const write = (cart) => {
    localStorage.setItem(CART_KEY, JSON.stringify(cart));
    updateBadge(cart);
  };

  const getTotals = (cart) => {
    const itemCount = cart.reduce((s, it) => s + it.qty, 0);
    // Prices are already in USD
    const subtotal = cart.reduce((s, it) => s + it.price * it.qty, 0);
    
    // Shipping in USD:
    // - Free shipping if order >= $20
    // - $1.2 if order < $20
    const FREE_SHIPPING_THRESHOLD = 20;
    const STANDARD_SHIPPING_FEE = 1.2;
    
    const shipping = subtotal >= FREE_SHIPPING_THRESHOLD ? 0 : (subtotal > 0 ? STANDARD_SHIPPING_FEE : 0);
    const total = subtotal + shipping;
    
    return { itemCount, subtotal, shipping, total };
  };

  const add = (product, qty = 1) => {
    const cart = read();
    const id = String(product.id);
    const idx = cart.findIndex((x) => x.id === id);
    if (idx >= 0) cart[idx].qty += qty;
    else
      cart.push({
        id,
        name: product.name,
        price: Number(product.price || 0),
        image: product.image || "",
        qty: Math.max(1, parseInt(qty || 1, 10)),
      });
    write(cart);
    return cart;
  };

  const setQty = (id, qty) => {
    const cart = read();
    const idx = cart.findIndex((x) => x.id === String(id));
    if (idx >= 0) {
      cart[idx].qty = Math.max(1, parseInt(qty || 1, 10));
      write(cart);
    }
    return cart;
  };

  const remove = (id) => {
    const cart = read().filter((x) => x.id !== String(id));
    write(cart);
    return cart;
  };

  const clear = () => {
    write([]);
    return [];
  };

  const updateBadge = (cart = null) => {
    const el = document.querySelector("#cart-count, .cart-count");
    if (!el) return;
    const { itemCount } = getTotals(cart ?? read());
    el.textContent = String(itemCount);
    el.style.display = itemCount > 0 ? "inline-flex" : "none";
  };

  // UI: Cart page
  const renderCartTable = () => {
    const cart = read();
    const tbody = document.querySelector("#cart-table-body");
    const emptyBox = document.getElementById("cart-empty");
    const tableWrap = document.getElementById("cart-table-wrap");
    const sumSub = document.getElementById("summary-subtotal");
    const sumShip = document.getElementById("summary-shipping");
    const sumTotal = document.getElementById("summary-total");

    if (!tbody) return;

    tbody.innerHTML = "";

    if (!cart.length) {
      if (tableWrap) tableWrap.classList.add("d-none");
      if (emptyBox) emptyBox.classList.remove("d-none");
    } else {
      if (tableWrap) tableWrap.classList.remove("d-none");
      if (emptyBox) emptyBox.classList.add("d-none");

      for (const item of cart) {
        const tr = document.createElement("tr");
        tr.innerHTML = `
          <td>
            <div class="d-flex align-items-center gap-3">
              <img src="${item.image || ""}" alt="${item.name}" onerror="this.style.display='none'" class="rounded" />
              <div>
                <div class="fw-semibold">${item.name}</div>
                <div class="text-muted small">Mã: ${item.id}</div>
              </div>
            </div>
          </td>
          <td class="text-end">${fmtCurrency(item.price)}</td>
          <td class="text-center">
            <div class="qty-control">
              <button class="btn btn-outline-secondary btn-sm" data-action="dec" data-id="${item.id}">-</button>
              <input class="form-control form-control-sm text-center" type="number" min="1" value="${item.qty}" data-id="${item.id}"/>
              <button class="btn btn-outline-secondary btn-sm" data-action="inc" data-id="${item.id}">+</button>
            </div>
          </td>
          <td class="text-end fw-semibold">${fmtCurrency(item.price * item.qty)}</td>
          <td class="text-center">
            <button class="btn btn-link text-danger p-0" data-action="remove" data-id="${item.id}" aria-label="Xóa">×</button>
          </td>
        `;
        tbody.appendChild(tr);
      }
    }

    const { subtotal, shipping, total } = getTotals(cart);
    if (sumSub) sumSub.textContent = fmtCurrency(subtotal);
    if (sumShip) sumShip.textContent = fmtCurrency(shipping);
    if (sumTotal) sumTotal.textContent = fmtCurrency(total);

    updateBadge(cart);
  };

  const bindCartEvents = () => {
    const tbody = document.querySelector("#cart-table-body");
    if (!tbody) return;

    tbody.addEventListener("click", (e) => {
      const btn = e.target.closest("button");
      if (!btn) return;
      const id = btn.getAttribute("data-id");
      const action = btn.getAttribute("data-action");
      if (!id || !action) return;
      const cart = read();
      const item = cart.find((x) => x.id === id);
      if (!item) return;
      if (action === "inc") setQty(id, item.qty + 1);
      if (action === "dec") setQty(id, Math.max(1, item.qty - 1));
      if (action === "remove") remove(id);
      renderCartTable();
    });

    tbody.addEventListener("input", (e) => {
      const input = e.target.closest("input[type=number]");
      if (!input) return;
      const id = input.getAttribute("data-id");
      const qty = parseInt(input.value || "1", 10);
      setQty(id, qty);
      renderCartTable();
    });

    const clearBtn = document.getElementById("btn-clear-cart");
    if (clearBtn) clearBtn.addEventListener("click", () => {
      if (confirm("Bạn có chắc muốn xóa toàn bộ giỏ hàng?")) {
        clear();
        renderCartTable();
      }
    });

    // Handle checkout button with login check
    const checkoutBtn = document.getElementById("btn-checkout");
    if (checkoutBtn) {
      checkoutBtn.addEventListener("click", () => {
        const isLoggedIn = checkoutBtn.getAttribute("data-logged-in") === "true";
        const cart = read();
        
        // Check if cart is empty
        if (!cart || cart.length === 0) {
          alert("Giỏ hàng của bạn đang trống!");
          return;
        }
        
        // Check if user is logged in
        if (!isLoggedIn) {
          const shouldLogin = confirm(
            "Bạn cần đăng nhập để tiếp tục thanh toán.\n\n" +
            "Nhấn OK để đến trang đăng nhập, hoặc Cancel để tiếp tục mua sắm."
          );
          
          if (shouldLogin) {
            // Redirect to login page with return URL
            window.location.href = "login.php?redirect=order.php";
          }
          return;
        }
        
        // If logged in, proceed to checkout
        window.location.href = "order.php";
      });
    }
  };

  const initCartPage = () => {
    renderCartTable();
    bindCartEvents();
  };

  // UI: Checkout page - REMOVED
  // All checkout functionality has been moved to checkout-stripe.js
  // including renderCheckoutSummary() and form submission handling.

  // Generic: buttons with data-add-to-cart
  const bindGlobalAddToCart = () => {
    document.body.addEventListener("click", (e) => {
      const btn = e.target.closest("[data-add-to-cart]");
      if (!btn) return;
      const product = {
        id: btn.getAttribute("data-id") || btn.dataset.id,
        name: btn.getAttribute("data-name") || btn.dataset.name,
        price: parseFloat(
          btn.getAttribute("data-price") || btn.dataset.price || "0"
        ),
        image:
          btn.getAttribute("data-image") || btn.dataset.image || "",
      };
      const qtyAttr = btn.getAttribute("data-qty") || btn.dataset.qty;
      const qty = qtyAttr ? parseInt(qtyAttr, 10) : 1;
      if (!product.id || !product.name) return;
      add(product, isNaN(qty) ? 1 : qty);
      // UX: brief toast
      try {
        const toast = document.createElement("div");
        toast.className = "toast add-to-cart-toast";
        toast.textContent = "Đã thêm vào giỏ hàng";
        document.body.appendChild(toast);
        setTimeout(() => toast.classList.add("show"), 10);
        setTimeout(() => toast.classList.remove("show"), 1600);
        setTimeout(() => toast.remove(), 2000);
      } catch {}
    });
  };

  // Public API
  const Cart = {
    read,
    write,
    add,
    setQty,
    remove,
    clear,
    getTotals,
    updateBadge,
  };

  // Expose for debugging and manual use
  window.Cart = Cart;
  window.addToCart = (p, q) => add(p, q);

  document.addEventListener("DOMContentLoaded", () => {
    updateBadge();
    bindGlobalAddToCart();
    const page = document.querySelector("[data-page]");
    const pageName = page ? page.getAttribute("data-page") : "";
    if (pageName === "cart") initCartPage();
    // Checkout page is handled by checkout-stripe.js
  });
})();
